### ISSUE TITLE
Discord sniper still does not work. Do I need to install 1.4.2 discord?

### ISSUE THREAD

**Issue by AYSTiC-dev** [Wh7sk/Alucard-SelfBot-Whisk-Edit#2]

**Comment by Wh7sk** [comment]
Yes you need to run the new setup.bat its required.

**Comment by AYSTiC-dev** [comment]
> Yes you need to run the new setup.bat its required.

I ran the setup and yet it's still on discord.py 1.7.2

**Comment by Wh7sk** [comment]
The setup / setup.bat process has been updated, check the READ.md and download the new setup.bat.

**Comment by AYSTiC-dev** [comment]
It is only crashing now, not opening. I reinstall, I think it gives me an error when i run setup, but on run.bat, it opens for a millisecond then closes.

**Comment by Wh7sk** [comment]
What version of python are you running?

**Comment by AYSTiC-dev** [comment]
Python 3.8

**Comment by Wh7sk** [comment]
Do you have any other python versions installed? also have latest version of pip?

**Comment by AYSTiC-dev** [comment]
> Do you have any other python versions installed? also have latest version of pip?

I'll try and reinstall it right now.

**Comment by AYSTiC-dev** [comment]
> Do you have any other python versions installed? also have latest version of pip?

Do you have discord and can I screenshare to you there? omar.# 0002
